view: config
id: EntityFileCFG
messages: tools.dynamia.modules.entityfile
fields:
    entityFileStorage:
        label: Storage
        component: storagebox
        params:
            parameterName: DEFAULT_STORAGE_ID
    filesLocation:
        label: Files Location
        description: Server directory in wich will be saved
        component: directorybox
        params:
            parameterName: LOCAL_FILES_LOCATION
    reportsLocation:
        label: Reports Location
        description: Server directory in wich will loaded
        component: directorybox
        params:
            parameterName: GLOBAL_REPORTS_LOCATION