view: config
id: EntityFileCFG
messages: tools.dynamia.modules.entityfile
fields:
  entityFileStorage:
    label: Storage
    component: storagebox
    params:
      parameterName: DEFAULT_STORAGE_ID
      cacheable: true
  filesLocation:
    label: Files Location
    description: Server directory in wich will be saved
    component: directorybox
    params:
      parameterName: LOCAL_FILES_LOCATION
      cacheable: true
  reportsLocation:
    label: Reports Location
    description: Server directory in wich will loaded
    component: directorybox
    params:
      parameterName: GLOBAL_REPORTS_LOCATION
      cacheable: true
  useHttps:
    label: Use HTTPS for Local Storage
    component: checkbox
    params:
      parameterName: LOCAL_USE_HTTPS
      cacheable: true